Sidebar/flyout menu - Scroll Dropdown + Bug Fixes
USACE/groundwork pull request #134
Opened 2024-11-19 16:19 UTC by krowvin

This PR addresses:
- #120
  - Add a scroll bar when the number of items would exceed 50% of the viewport height
  - Correct font mismatch for size/weight by making links with no children in the same menu
- #126 
  - Fixed links so when a link is clicked that does not cause a full page refresh it will properly close sidebar

Started to go to vanilla method but that was a "hover" approach. Decided to keep with headlessui as we use it in other places. Fix was to ensure children are `fixed` instead of `absolute` (Parent must still be absolute)

2024-11-20 20:17 UTC, willbreitkreutz requested changes

2024-11-20 20:17 UTC, willbreitkreutz commented on lib/composite/sidebar/index.jsx
> +          {link.children && (
I kind of think we only want the chevron when using the popout, it's sort of confusing in the default configuration because I see it and assume it's part of an accordion that should expand/contract.  Open to pushback though.

2024-11-20 20:17 UTC, willbreitkreutz commented on src/example-links.js
Can we get a shorter list of links in the example docs for the no-popout version?  I get that its showing the differences, but makes it kind of onerous to scroll down to the props table, maybe replace the middle half of links with a single link with the text of `...` or something?  just a thought, not a dealbreaker.

2024-11-22 16:27 UTC, krowvin commented
@willbreitkreutz Ready for review - fixes should be implemented.

2024-11-25 15:49 UTC, willbreitkreutz approved these changes
Thanks

2024-11-25 15:49 UTC, willbreitkreutz commented on lib/composite/sidebar/index.jsx
> +            options={combinedLinks.map((link, idx) => (
Makes sense not to use href as the key, no guarantee they will be unique.  using idx _could_ open up issues down the road, if you wanted to programmatically update the links, it wouldn't work because the keys wouldn't change.  Probably not a big deal in 99.9% of cases, but knowing us we'll find the edge case sooner than later.  Could do a combo of the href and idx?

2024-12-02 16:28 UTC, willbreitkreutz approved these changes

2024-12-02 16:28 UTC, merged