Link Provider
USACE/groundwork pull request #142
Opened 2024-12-16 16:29 UTC by jbkolze

Provide a way to abstract link components by wrapping the user's site in a `<LinkProvider />`.

Tested against LRL's site using React Router and against Groundwork's internal docs without noticing any issues, but further testing might not be a bad idea since it could potentially break a lot.  Seems to work as far as I can tell, though.

Provided docs mostly explain what's going on, but can provide clarification if needed.

2025-01-27 16:06 UTC, willbreitkreutz requested changes

2025-01-27 16:06 UTC, willbreitkreutz commented on src/app-pages/documentation/navigation/link-provider.jsx
The docs are good for setting up the router, but they don't really explain where/how to use the `clientRouter` in your app, I think we just need to add that in and its good.

2025-01-27 17:39 UTC, jbkolze commented on src/app-pages/documentation/navigation/link-provider.jsx
Added

2025-02-03 16:02 UTC, willbreitkreutz approved these changes

2025-02-03 16:33 UTC, merged