Add sidebar and breadcrumbs to Container
USACE/groundwork pull request #79
Opened 2024-06-21 04:10 UTC by krowvin

# Revisions 
- Added syntax highlighting for \<Code\>  
- Added flag to disable clipboard copying of source comments  
- Added sidebar/breadcrumbs to \<Container\>  
- Made it so `hash` or `pathname` would work for the container 

I was uncertain if I should make a <Sidebar> page to show how to import sidebar and then expect endusers to wrap it like you had it before in `_docs-page.jsx`. I ended up making it an optional part of the Container. 

⚠ We may also want to consider forcing fluid to `off` when `sidebar` is present to prevent a lack of real-estate for the sidebar.
 
🧪 Tested this in local environment 
 
Solves 
 - #78

2024-06-21 04:11 UTC, krowvin commented on lib/composite/sidebar/index.jsx
> +        const isSelected = hash === link.href || pathname === link.href;
I wasn't 100% what would happen if users were not using `selectHash` so opted to check for hash first, then pathname.

2024-06-21 04:12 UTC, krowvin commented on lib/components/display/text.jsx
> +import { Prism } from "react-syntax-highlighter";
react-syntax-highlighter looks to be a wrapper for prism.js - could be wrong here. 

Seemed to be the best option I could find and has an active website still
https://prismjs.com/

2024-06-21 04:14 UTC, krowvin commented on src/app-pages/documentation/layout/container.jsx
> +  },
These lines (`type`) are what got me to add the syntax highlighter. I wanted to be able to get more detailed with the type and not have it all on one line. 

The other codeblocks also benefit

2024-06-24 16:24 UTC, willbreitkreutz commented
Hey @krowvin I've got a couple thoughts moving forward with this one.

1. Can we separate the code highlighting from the sidebar PR?  I'd prefer if we could treat them as separate issues.  I'm a little hesitant on the `react-syntax-highlighter` lib, it adds almost 2x as many bytes as groundwork is by itself.  Not that the value it adds isn't worth it, but I think it warrants a separate discussion.
2. I'd prefer keeping the sidebar and breadcrumbs outside of the site wrapper and compose them together rather than make them options... Just my spidey senses tingling that it's backing users into a corner and will break some cases where we want sidebars on some pages, but not all etc...

2024-06-28 22:05 UTC, krowvin commented
> I'd prefer if we could treat them as separate issues  

I agree - I should have done that. Wasn't trying to sneak it in either. But looking at the doc code had me thinking it might be nice. I'll do some more research on the syntax highligher. Surely since it's a React library some treeshaking can go down so it's not pulling in all the file types (only the ones we need) i.e. JSX, JS, and maybe bash. 
For now I stripped out the commits and force pushed over them as to not pollute the commit history. (assuming you don't do a squash)

Cherrypicked the commits into a sep branch for testing later: 
https://github.com/USACE/groundwork/tree/features/syntax-highlighting

> I'd prefer keeping the sidebar and breadcrumbs outside of the site wrapper and compose them together rather than make them options  
I struggled to decide on this. I was hoping to just have sidebar be a component you could use *with* the others when you wanted. But could not find a clean way to add the grid layout you had so the user wouldn't have to do that. But maybe that's the answer, to have that grid in the example. 

I went ahead and resubmitted with Sidebar outside of the site wrapper/container.

to something like this
```jsx
import { UsaceBox, Sidebar } from "@usace/groundwork";
import sidebarLinks from "./sidebarLinks";
<Container fluid>
    <div className="gw-grid gw-grid-cols-12 gw-gap-6">
        <div className="gw-hidden md:gw-block md:gw-col-span-2">
            <Sidebar sidebarLinks={sidebarLinks} />
        </div>
        <div className="gw-col-span-12 md:gw-col-span-10">
            <UsaceBox title="Sidebar Example">
                Hello World
            </UsaceBox>
        </div>
    </div>
</Container>
```

2024-07-08 15:00 UTC, willbreitkreutz requested changes
Late review, sorry, just a few updates then this should work.

2024-07-08 15:00 UTC, willbreitkreutz commented on lib/composite/sidebar/index.jsx
> +        const isSelected = hash === link.href || pathname === link.href;
I was thinking we would move the `isSelected` logic out of the sidebar component and let the consumer provide that as part of the `link` objects.

2024-07-08 15:00 UTC, willbreitkreutz commented on lib/composite/sidebar/index.jsx
> +                  isSelected ? "gw-bg-gray-50 gw-rounded" : ""
So that would make this `link.isSelected ? ...`

2024-07-08 15:00 UTC, willbreitkreutz commented on lib/composite/sidebar/index.jsx
> +                    hash === child.href || pathname === child.href;
Same sort of thing here, `const isChildSelected = child.isSelected;`

2024-07-08 15:00 UTC, willbreitkreutz commented on package.json
> +  "version": "2.5.4",
Let's wait to bump versions until we merge all pull requests during the call on mondays.

2024-07-08 15:00 UTC, willbreitkreutz commented on src/nav-links.js
> +      },
If we move the `isSelected` logic here, then i'd probably refactor this file so that it exports a function that can be called when you want to render the links, the function would implement the logic looking at the hash and comparing the href and populating the `isSelected` key on each link.

2024-07-08 15:00 UTC, willbreitkreutz commented on src/app-pages/documentation/navigation/sidebar.jsx
> +        <div className="gw-rounded-md gw-border gw-border-dashed gw-px-6 gw-py-3 gw-mb-3"></div>
Typically I'd put an example here, so, whatever example code is below, you would put here so that users can see the output.

I'd probably just have one parent link with one or two children, rather than reference the `sidebarLinks` object, that way they get a good look at what those link objects should look like.

2024-07-08 15:00 UTC, willbreitkreutz commented on src/app-pages/documentation/_docs-page.jsx
> +import  sidebarLinks  from "../../nav-links";
If we refactor `nav-links` to export a function then that adds one more line here where we import the function then call it to populate the `sidebarLinks` array.

2024-07-08 15:36 UTC, krowvin commented on lib/composite/sidebar/index.jsx
> +        const isSelected = hash === link.href || pathname === link.href;
Got it, adding a isSelected key to the object

2024-07-22 20:18 UTC, willbreitkreutz approved these changes

2024-07-22 20:19 UTC, willbreitkreutz approved these changes

2024-07-25 17:13 UTC, jbkolze approved these changes

2024-07-29 15:24 UTC, merged